### ISSUE TITLE
Move to setuptools-rust as build dependency

### ISSUE THREAD

**Issue by kushaldas** [kushaldas/johnnycanencrypt#101]
`maturin` is not packaged in Fedora or Debian. [setuptools-rust](https://setuptools-rust.readthedocs.io/en/latest/) will help us to package `jce` easily in both the distributions.

**Comment by dkg** [comment]
note [Jelmer is trying to land `maturin` in debian](https://bugs.debian.org/999850).  i still think moving to `setuptols-rust` will make things easier for you going forward, so this seems reasonable to me.
