### ISSUE TITLE
Consider adding Cargo.lock to repo

### ISSUE THREAD

**Issue by dotlambda** [kushaldas/johnnycanencrypt#125]
Since johnnycanencrypt is not supposed to be used by other Rust projects, its Cargo.lock should be committed and removed from .gitignore: https://github.com/rust-lang/cargo/issues/315
This would help with packaging the Python module in a reproducible way.

**Comment by kushaldas** [comment]
Thank you @dotlambda for opening the issue. Will fix this.

**Comment by dvzrv** [comment]
This would be really great to have for packaging this project on downstream distributions! :)

**Comment by kushaldas** [comment]
This is done.

**Comment by dotlambda** [comment]
> This is done.

It's not: https://github.com/kushaldas/johnnycanencrypt/blob/main/Cargo.lock
