### ISSUE TITLE
Relicensing the project to LGPL

### ISSUE THREAD

**Issue by kushaldas** [kushaldas/johnnycanencrypt#126]
As [sequoia](https://gitlab.com/sequoia-pgp/sequoia) is now under LGPL, I think we can move into LGPL 3.0 or later license.

@anarcat @euri10 @anweshadas @SaptakS Please comment in the issue that you would be okay with the relicensing.

**Comment by SaptakS** [comment]
I am fine with it.

**Comment by euri10** [comment]
I honestly dont have any idea so I cant really comment !

**Comment by kushaldas** [comment]
> I honestly dont have any idea so I cant really comment !

@euri10 I need your permission as you contributed to the project, if you don't have any preference, then can you please say "Yes, I agree" in this thread.

**Comment by anweshadas** [comment]
This is absolutely fine with me.

**Comment by euri10** [comment]
> > I honestly dont have any idea so I cant really comment !
> 
> @euri10 I need your permission as you contributed to the project, if you don't have any preference, then can you please say "Yes, I agree" in this thread.

roooo I didn't understand that sorry !
Yes I agree of course !
and thanks for the great project :)
