### ISSUE TITLE
ks.get_key(None) returns the 1st key

### ISSUE THREAD

**Issue by euri10** [kushaldas/johnnycanencrypt#146]
which given the way `_internal_get_key` is logical (this is the else case and the sql query fetches all keys) but does that make sense from a user perspective ?
I was surprised to see this behaviour and would have expected a KeyNotFoundError instead.

Current implementation of _internal_get_key also has a allkeys parameters but it is not used.

I wrote a little PR that uses that parameter and raise a KeyNotFoundError if get_key gets passed a None

**Comment by kushaldas** [comment]
Bug introduced by me.
