### ISSUE TITLE
Allow multiple UIDs while creating a new key

### ISSUE THREAD

**Issue by kushaldas** [kushaldas/johnnycanencrypt#40]
Right now we allow only one UID (as string value) while generating a new key. We should allow multiple UIDs while generating a new key.

**Comment by nwalfield** [comment]
If you have a convenient interface to add additional User IDs, then this is not necessary.

You might want to consider support User ID-less certificates, for which there is limited, but not universal, support in the ecosystem.   https://tests.sequoia-pgp.org/#Default_key_generation__encrypt-decrypt_roundtrip__no_UIDs
