### ISSUE TITLE
Use Sequoia's public key store

### ISSUE THREAD

**Issue by nwalfield** [kushaldas/johnnycanencrypt#72]
Sequoia now has a public key store (well almost).  We wrote a [specification]https://sequoia-pgp.gitlab.io/pgp-cert-d/) to
encourage interoperability.  The [implementation](https://gitlab.com/sequoia-pgp/pgp-cert-d) is mostly complete.  It would be nice if JCE either used the pgp-cert-d crate or implemented the specification rather than using a custom solution.

**Comment by nwalfield** [comment]
There is now a higher-level API: https://gitlab.com/sequoia-pgp/sequoia-cert-store

**Comment by kushaldas** [comment]
For now we will close this as the work required to move the jce code base to something is big. Also as normal Python part of the code, keeping the certs in SQLite3 solves the problem jce is solving now (and easier to maintain).
