### ISSUE TITLE
sign key

### ISSUE THREAD

**Issue by euri10** [kushaldas/johnnycanencrypt#86]
greetings,
what  would be the "equivalent" in this nice library of `sign_key` here (https://pythonhosted.org/gnupg/gnupg.html#gnupg.GPG.sign_key) please ?

**Comment by kushaldas** [comment]
Ah, we don't have this feature yet. Maybe in a future release.

**Comment by euri10** [comment]
> @euri10 Ah, we don't have this feature yet. Maybe in a future release.

would be nice, thanks !

**Comment by kushaldas** [comment]
@euri10 I am planning to add functions to sign the given user IDs for a given key, following https://docs.rs/sequoia-openpgp/1.10.0/sequoia_openpgp/packet/prelude/struct.UserID.html#method.certify

**Comment by dkg** [comment]
see also https://gitlab.com/dkg/openpgp-stateless-cli/-/issues/44

**Comment by kushaldas** [comment]
We need #104 first.

**Comment by kushaldas** [comment]
As per the chat on #sequoia channel, I will go forward without `Trust amount` & `Trust depth` for now, will only have standard certifying of user ids using various SignatureType for certification (default will be [GenericCertification](https://docs.rs/sequoia-openpgp/1.10.0/sequoia_openpgp/types/enum.SignatureType.html)).
